In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline


In [2]:
train = pd.read_csv('train.csv')

In [3]:
train.head()

id                                       comment_text  toxic  \
0  22256635  Nonsense?  kiss off, geek. what I said is true...      1   
1  27450690  "\n\n Please do not vandalize pages, as you di...      0   
2  54037174  "\n\n ""Points of interest"" \n\nI removed the...      0   
3  77493077  Asking some his nationality is a Racial offenc...      0   
4  79357270  The reader here is not going by my say so for ...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer


In [5]:
count = CountVectorizer()
comments = np.array(train['comment_text'])
bag = count.fit_transform(comments)

In [6]:
#print(count.vocabulary_)
#print(bag.toarray())

In [105]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf = TfidfTransformer()
np.set_printoptions(precision=8)
print(tfidf.fit_transform(count.fit_transform(comments)).toarray())

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [8]:
# from nltk.stem.porter import PorterStemmer
# from nltk.corpus import stopwords

# porter = PorterStemmer()
# stop = stopwords.words('english')

# def tokenizer(text):
#     return text.split()
# def tokenizer_porter(text):
#     return [porter.stem(word) for word in text.split()]

In [106]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
import pickle
import os
from time import time
from mylib.tokenizer import tokenizer, tokenizer_porter

train = pd.read_csv('train.csv')
toxic_classes = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

for toxic_class in toxic_classes:

    X_train = train.loc[:35000, 'comment_text'].values
    y_train = train.loc[:35000, toxic_class].values
    X_test = train.loc[15000:, 'comment_text'].values
    y_test = train.loc[15000:, toxic_class].values

    tfidf = TfidfVectorizer(lowercase=False, tokenizer=tokenizer)
    lr_tfidf = Pipeline([('vect',tfidf),('clf',LogisticRegression(C=10.0, penalty='l2', random_state=0))])

    stime = time()
    print('fitting begins for {}'.format(toxic_class))
    lr_tfidf.fit(X_train, y_train)
    print('fitting done')

    y_pred = lr_tfidf.predict(X_test)
    print ('time consumption= [%d] seconds'%(time()-stime))
    print ('accuracy= %.3f'%accuracy_score(y_test,y_pred))

    print('c-v completed')
    print('-'*50)

fitting begins for toxic
fitting done
time consumption= [6] seconds
accuracy= 0.960
c-v completed
--------------------------------------------------
fitting begins for severe_toxic
fitting done
time consumption= [5] seconds
accuracy= 0.992
c-v completed
--------------------------------------------------
fitting begins for obscene
fitting done
time consumption= [5] seconds
accuracy= 0.977
c-v completed
--------------------------------------------------
fitting begins for threat
fitting done
time consumption= [5] seconds
accuracy= 0.998
c-v completed
--------------------------------------------------
fitting begins for insult
fitting done
time consumption= [5] seconds
accuracy= 0.973
c-v completed
--------------------------------------------------
fitting begins for identity_hate
fitting done
time consumption= [5] seconds
accuracy= 0.993
c-v completed
--------------------------------------------------


In [114]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
import pickle
import os
from time import time
from mylib.tokenizer import tokenizer, tokenizer_porter

train = pd.read_csv('train.csv')
test0 = pd.read_csv('test.csv')
test = test0['comment_text'].fillna(' ')
np.array(test)

toxic_classes = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']

for toxic_class in toxic_classes:

    X_train = train['comment_text']
    y_train = train[toxic_class]
    

    tfidf = TfidfVectorizer(lowercase=False, tokenizer=tokenizer)
    lr_tfidf = Pipeline([('vect',tfidf),('clf',LogisticRegression(C=10.0, penalty='l2', random_state=0))])

    stime = time()
    print('fitting begins')
    lr_tfidf.fit(X_train, y_train)
    print('fitting done')

    y_pred = lr_tfidf.predict_proba(test)
    print ('time consumption= [%d] seconds'%(time()-stime))
    print ('prediction complited')
    
    print (y_pred)
    
    test0['{}'.format(toxic_class)] = pd.Series(list(y_pred[:,1]))
    

    print('classification completed')
    print('-'*50)

fitting begins
fitting done
time consumption= [18] seconds
prediction complited
[[  9.91177650e-01   8.82234955e-03]
 [  9.96607776e-01   3.39222420e-03]
 [  9.98638965e-01   1.36103490e-03]
 ..., 
 [  9.96208556e-01   3.79144389e-03]
 [  9.31948321e-01   6.80516793e-02]
 [  9.99619466e-01   3.80534442e-04]]
classification completed
--------------------------------------------------
fitting begins
fitting done
time consumption= [18] seconds
prediction complited
[[  9.96129083e-01   3.87091716e-03]
 [  9.99759918e-01   2.40081617e-04]
 [  9.99675734e-01   3.24266248e-04]
 ..., 
 [  9.99821956e-01   1.78043949e-04]
 [  9.96106156e-01   3.89384420e-03]
 [  9.99976129e-01   2.38707632e-05]]
classification completed
--------------------------------------------------
fitting begins
fitting done
time consumption= [16] seconds
prediction complited
[[  9.82175533e-01   1.78244666e-02]
 [  9.98221626e-01   1.77837388e-03]
 [  9.98665630e-01   1.33437007e-03]
 ..., 
 [  9.89707809e-01   1.0292190

In [116]:
test0.head()

id                                       comment_text     toxic  \
0   6044863  ==Orphaned non-free media (Image:41cD1jboEvL. ...  0.008822   
1   6102620  ::Kentuckiana is colloquial.  Even though the ...  0.003392   
2  14563293  Hello fellow Wikipedians,\nI have just modifie...  0.001361   
3  21086297  AKC Suspensions \nThe Morning Call - Feb 24, 2...  0.018333   
4  22982444                      == [WIKI_LINK: Talk:Celts] ==  0.233255   

   severe_toxic   obscene    threat    insult  identity_hate  
0      0.003871  0.017824  0.001901  0.013543       0.002310  
1      0.000240  0.001778  0.000191  0.000331       0.000684  
2      0.000324  0.001334  0.000169  0.001193       0.000301  
3      0.002446  0.007279  0.001326  0.009122       0.002905  
4      0.005540  0.060772  0.000430  0.063316       0.003992

In [117]:
del test0['comment_text']
test0.to_csv('first_answer.csv', index = False)

In [118]:
import pickle
import os
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score

train = pd.read_csv('train.csv')

X_train = train.loc[:35000, 'comment_text'].values
y_train = train.loc[:35000, 'toxic'].values
X_test = train.loc[15000:, 'comment_text'].values
y_test = train.loc[15000:, 'toxic'].values


curDir = os.getcwd()
clf = pickle.load(open(os.path.join(curDir, 'data','pklObject', 'classfier.pkl'),'rb'))

y_pred = clf.predict(X_test)
print ('accuracy= %.3f'%accuracy_score(y_test,y_pred))

label = {0: 'not toxic', 1: 'toxic'}

while True:
    txt = input('write your own comment: ')
    if txt == "":
        break
    
    example = [txt]
    print ('prediction= %s\nprobability= %.3f%%'%(label[clf.predict(example)[0]],np.max(clf.predict_proba(example))*100))


accuracy= 0.960
write your own comment: 
